### ISSUE TITLE
"Conditional read not allowed" error

### ISSUE THREAD

**Issue by onetom** [SevereOverfl0w/high#12]
Reproduce:
```bash
nix-shell -p clojure --run "clj -Sdeps '{:deps {org.clojure/tools.namespace {:mvn/version \"1.0.0\"} juxt/clip {:mvn/version \"0.17.0\"}}}' -e \"(use 'juxt.clip.repl)\""
Syntax error reading source at (juxt/clip/repl.clj:57:5).
Conditional read not allowed
```
which is this line:
https://github.com/juxt/clip/blob/master/src/juxt/clip/repl.clj#L57
from this code block:
```clojure
(defn- ->deref
  [deref]
  #?(:cljs deref
     :default
     (if (fn? deref)
       deref
       (requiring-resolve deref))))
```

**Comment by onetom** [comment]
This error has manifested during the documentation CI pipeline too:
* https://cljdoc.org/builds/31532
* https://app.circleci.com/pipelines/github/cljdoc/builder/6387/workflows/1d5fc2b5-b6d5-4cf8-9665-590e42c83ee1/jobs/22763/steps
```
ERROR STDERR
 Execution error at cljdoc-analyzer.metagetta.clojure/read-ns (clojure.clj:100).
Conditional read not allowed
```
I'm not yet sure how to write a test for this though.

**Comment by SevereOverfl0w** [comment]
Hmph.  That was stupid of me.  Not sure how that got past my testing.
