### ISSUE TITLE
no tools.namespace in deps.edn - juxt.clip.repl fails

### ISSUE THREAD

**Issue by frap** [SevereOverfl0w/high#20]
trying out 1st option (aka repl) on startrek get juxt.clip.repl error in that tools/namespace/repl isnt available. Fixed it in startrek by adding  org.clojure/tools.namespace {:mvn/version "1.1.0"} to startrek deps - but it should be a dependency of clip no?

**Comment by SevereOverfl0w** [comment]
Sorry that this tripped you up. Its optional dependency of clip, you need to add it yourself if you're using that namespace.

This is documented under https://github.com/juxt/clip#reloaded

> Clip provides a namespace for easily setting up a reloaded workflow. You will need to add a dependency on tools.namespace to your project.

Closing as I can't think of a way to make this clearer, but if you can, please let me know!

**Comment by frap** [comment]
Ok

Sorry didnt read far enough down on clip.

Regards A
---
Gas ***@***.***
Home: PP6R+7P
+64 21 629488
If there is no track, you can’t be off track.
