### ISSUE TITLE
Provide way to provide "everything so far"

### ISSUE THREAD

**Issue by bowbahdoe** [SevereOverfl0w/high#30]
[This conversation](https://clojurians.slack.com/archives/C03S1KBA2/p1648146414074119) in clojurians can give context, but basically It would be nice to be able to pass "everything so far" to the start mechanism of a component

**Comment by SevereOverfl0w** [comment]
I'm not keen on this feature, for the same reason as #9 wasn't implemented: explicit is better.  If there's a change I can make to accommodate doing this in user-space better then I'm happy to do so.

I have thought a little bit about dependencies in this sense.  Specifically I was thinking about http routers which ideally wouldn't need lots of duplication to make them work.  My thinking was that components could request to participate in the dependency flow to generate themselves.  This gives a lot of flexibility wrt dynamism.
