### ISSUE TITLE
error when stopping a component that contains a list

### ISSUE THREAD

**Issue by henryw374** [SevereOverfl0w/high#7]
here's a repro system config:
```
(def my-config 
{:components {:x {:start `(hash-map 1 (list 1))
                                :stop (list identity 'this)}}})
```

on stopping, it's trying to exec the list in the system, 'Unsupported callable 1'

This might look like an esoteric repro but the component in question was actually a pedestal server - which happened to reference a list. 

btw Thanks for the lib!

**Comment by SevereOverfl0w** [comment]
I see. Hmm. Might need to roll back the new executor. I would imagine 0.10.0 would work for you.
