### ISSUE TITLE
[Feature] Implement `clip/refs` or `clip/refset` to return all refs derived from a keyword

### ISSUE THREAD

**Issue by kirillsalykin** [SevereOverfl0w/high#9]
Similar to https://github.com/weavejester/integrant#refs-vs-refsets

Currenlty ref returns only one thing, it would be nice to have ability to reference multiple things.

```
(clip/start
   {:components '{:foo1 {:start (constantly :foo1)}
                  :foo2 {:start (constantly :foo2)}
                  :foo3 {:start (constantly :foo3)}
                  :foob {:start (clip/refs :foo)}}})
```

So `foob` accepts `[foo1 foo2 foo3]` or maybe event better `{:foo1 <resolved>, :foo2 <resolved> , :foo3 <resolved>}`.

**Comment by SevereOverfl0w** [comment]
Why not build that up manually? Clip doesn't use keyword derivation, and being explicit about the used components seems useful.

What's the use-case?

**Comment by kirillsalykin** [comment]
The use case is next:

for instance there is an `executor` service (which executes actions) and there are several `action`s.
Thus, the `executor` has `action`s as a dependency.

But probably indeed it is easier to have them added manually...

Thanks.

**Comment by SevereOverfl0w** [comment]
The reason I would encourage you to go manual is that refset creates a implicit link between things. The way it is written makes the link harder to see.

Besides, it falls apart when you have two executors.

It is annoying to duplicate, but I think the explicit flow is worth it in the long term.

**Comment by kirillsalykin** [comment]
I agree that explicit is better.

Thanks for the answer.
